blueprint:
  name: Motion activated switch with night sensor
  description: Turn on a switch when motion is detected, but only at night
  domain: automation
  source_url: https://raw.githubusercontent.com/algirdasc/ha-blueprints/refs/heads/main/motion_switch_with_night_sensor.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - motion
          multiple: false
    night_entity:
      name: Night Sensor
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    switch_target:
      name: Switch
      selector:
        target:
          entity:
          - domain:
            - switch
    no_motion_wait:
      name: Wait time
      description: Time to leave the switch on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
mode: restart
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input motion_entity
  from: 'off'
  to: 'on'
condition:
- condition: state
  entity_id: !input night_entity
  state: 'on'
action:
- service: switch.turn_on
  target: !input switch_target
- wait_for_trigger:
    platform: state
    entity_id: !input motion_entity
    from: 'on'
    to: 'off'
- delay: !input no_motion_wait
- service: switch.turn_off
  target: !input switch_target
